name: SSH and Gradle Build

on:
  workflow_run:
    workflows: ["Java CI with Gradle "]
    types:
      - completed

jobs:
  build:
    name: SSH and Build
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into server and run Gradle build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ulu/ULU/ua-backend/
            ./gradlew build
            systemctl restart your-service-name
